spring.application.name=PRESCRIPTION-SERVICE

server.port=8084


# ===============================
# H2 DATABASE
# ===============================

spring.datasource.url=jdbc:h2:mem:prescriptiondb

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=


# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# ===============================
# H2 CONSOLE
# ===============================

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console


# ===============================
# EUREKA
# ===============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=localhost:${server.port}
eureka.instance.status-page-url-path=/


# ===============================
# ACTUATOR
# ===============================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always


# ===============================
# APPLICATION INFO
# ===============================

info.app.name=MediFlow Prescription Service

info.app.description=Prescription Management Microservice

info.app.version=1.0.0

management.info.env.enabled=true
