# ===============================
# APPLICATION
# ===============================

spring.application.name=EUREKA-SERVER

server.port=8761


# ===============================
# EUREKA SERVER
# ===============================

# Eureka Server must not register itself.

eureka.client.register-with-eureka=false

# Eureka Server does not need to fetch registry information
# from another Eureka Server.

eureka.client.fetch-registry=false


# ===============================
# EUREKA INSTANCE
# ===============================

eureka.instance.hostname=localhost


# ===============================
# EUREKA SERVER SETTINGS
# ===============================

# Useful for a local development/demo environment.

eureka.server.enable-self-preservation=false

eureka.server.eviction-interval-timer-in-ms=5000


# ===============================
# ACTUATOR
# ===============================

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always


# ===============================
# APPLICATION INFO
# ===============================

info.app.name=MediFlow Eureka Server

info.app.description=Service Discovery Server for MediFlow Microservices

info.app.version=1.0.0

management.info.env.enabled=true
